<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webuser.proto

namespace WebUser;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>WebUser.GRPCReadWebUserResponse</code>
 */
class GRPCReadWebUserResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .WebUser.GRPCWebUserList webuserlist = 1;</code>
     */
    private $webuserlist;
    /**
     * Generated from protobuf field <code>string status = 2;</code>
     */
    protected $status = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \WebUser\GRPCWebUserList[]|\Google\Protobuf\Internal\RepeatedField $webuserlist
     *     @type string $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Webuser::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .WebUser.GRPCWebUserList webuserlist = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWebuserlist()
    {
        return $this->webuserlist;
    }

    /**
     * Generated from protobuf field <code>repeated .WebUser.GRPCWebUserList webuserlist = 1;</code>
     * @param \WebUser\GRPCWebUserList[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWebuserlist($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \WebUser\GRPCWebUserList::class);
        $this->webuserlist = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 2;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

}

