<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webuser.proto

namespace WebUser;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>WebUser.GRPCWebUserList</code>
 */
class GRPCWebUserList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string clientid = 2;</code>
     */
    protected $clientid = '';
    /**
     * Generated from protobuf field <code>string clientname = 3;</code>
     */
    protected $clientname = '';
    /**
     * Generated from protobuf field <code>string name = 4;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string email = 5;</code>
     */
    protected $email = '';
    /**
     * Generated from protobuf field <code>string password = 6;</code>
     */
    protected $password = '';
    /**
     * Generated from protobuf field <code>string privilegeid = 7;</code>
     */
    protected $privilegeid = '';
    /**
     * Generated from protobuf field <code>string privilege = 8;</code>
     */
    protected $privilege = '';
    /**
     * Generated from protobuf field <code>bool isactive = 9;</code>
     */
    protected $isactive = false;
    /**
     * Generated from protobuf field <code>bool isdelete = 10;</code>
     */
    protected $isdelete = false;
    /**
     * Generated from protobuf field <code>string createdate = 11;</code>
     */
    protected $createdate = '';
    /**
     * Generated from protobuf field <code>string updatedate = 12;</code>
     */
    protected $updatedate = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $clientid
     *     @type string $clientname
     *     @type string $name
     *     @type string $email
     *     @type string $password
     *     @type string $privilegeid
     *     @type string $privilege
     *     @type bool $isactive
     *     @type bool $isdelete
     *     @type string $createdate
     *     @type string $updatedate
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Webuser::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string clientid = 2;</code>
     * @return string
     */
    public function getClientid()
    {
        return $this->clientid;
    }

    /**
     * Generated from protobuf field <code>string clientid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setClientid($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string clientname = 3;</code>
     * @return string
     */
    public function getClientname()
    {
        return $this->clientname;
    }

    /**
     * Generated from protobuf field <code>string clientname = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setClientname($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 4;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 5;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password = 6;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string privilegeid = 7;</code>
     * @return string
     */
    public function getPrivilegeid()
    {
        return $this->privilegeid;
    }

    /**
     * Generated from protobuf field <code>string privilegeid = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setPrivilegeid($var)
    {
        GPBUtil::checkString($var, True);
        $this->privilegeid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string privilege = 8;</code>
     * @return string
     */
    public function getPrivilege()
    {
        return $this->privilege;
    }

    /**
     * Generated from protobuf field <code>string privilege = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setPrivilege($var)
    {
        GPBUtil::checkString($var, True);
        $this->privilege = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isactive = 9;</code>
     * @return bool
     */
    public function getIsactive()
    {
        return $this->isactive;
    }

    /**
     * Generated from protobuf field <code>bool isactive = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsactive($var)
    {
        GPBUtil::checkBool($var);
        $this->isactive = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isdelete = 10;</code>
     * @return bool
     */
    public function getIsdelete()
    {
        return $this->isdelete;
    }

    /**
     * Generated from protobuf field <code>bool isdelete = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsdelete($var)
    {
        GPBUtil::checkBool($var);
        $this->isdelete = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string createdate = 11;</code>
     * @return string
     */
    public function getCreatedate()
    {
        return $this->createdate;
    }

    /**
     * Generated from protobuf field <code>string createdate = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedate($var)
    {
        GPBUtil::checkString($var, True);
        $this->createdate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string updatedate = 12;</code>
     * @return string
     */
    public function getUpdatedate()
    {
        return $this->updatedate;
    }

    /**
     * Generated from protobuf field <code>string updatedate = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedate($var)
    {
        GPBUtil::checkString($var, True);
        $this->updatedate = $var;

        return $this;
    }

}

