<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: adminauth.proto

namespace XXX;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>XXX.AdminLoginRequest</code>
 */
class AdminLoginRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string email = 1;</code>
     */
    protected $email = '';
    /**
     * Generated from protobuf field <code>string password = 2;</code>
     */
    protected $password = '';
    /**
     * Generated from protobuf field <code>string remoteipaddress = 3;</code>
     */
    protected $remoteipaddress = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $email
     *     @type string $password
     *     @type string $remoteipaddress
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Adminauth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string email = 1;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password = 2;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string remoteipaddress = 3;</code>
     * @return string
     */
    public function getRemoteipaddress()
    {
        return $this->remoteipaddress;
    }

    /**
     * Generated from protobuf field <code>string remoteipaddress = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRemoteipaddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->remoteipaddress = $var;

        return $this;
    }

}

