<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: adminauth.proto

namespace XXX;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>XXX.AdminCheckSessionRequest</code>
 */
class AdminCheckSessionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string email = 1;</code>
     */
    protected $email = '';
    /**
     * Generated from protobuf field <code>string remoteipaddress = 2;</code>
     */
    protected $remoteipaddress = '';
    /**
     * Generated from protobuf field <code>string sessionid = 3;</code>
     */
    protected $sessionid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $email
     *     @type string $remoteipaddress
     *     @type string $sessionid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Adminauth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string email = 1;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string remoteipaddress = 2;</code>
     * @return string
     */
    public function getRemoteipaddress()
    {
        return $this->remoteipaddress;
    }

    /**
     * Generated from protobuf field <code>string remoteipaddress = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRemoteipaddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->remoteipaddress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sessionid = 3;</code>
     * @return string
     */
    public function getSessionid()
    {
        return $this->sessionid;
    }

    /**
     * Generated from protobuf field <code>string sessionid = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionid($var)
    {
        GPBUtil::checkString($var, True);
        $this->sessionid = $var;

        return $this;
    }

}

