<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto

namespace Client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Client.GRPCReadCurrencyResponse</code>
 */
class GRPCReadCurrencyResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Client.GRPCCurrencyList currencylist = 1;</code>
     */
    private $currencylist;
    /**
     * Generated from protobuf field <code>string status = 2;</code>
     */
    protected $status = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Client\GRPCCurrencyList[]|\Google\Protobuf\Internal\RepeatedField $currencylist
     *     @type string $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Client::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Client.GRPCCurrencyList currencylist = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCurrencylist()
    {
        return $this->currencylist;
    }

    /**
     * Generated from protobuf field <code>repeated .Client.GRPCCurrencyList currencylist = 1;</code>
     * @param \Client\GRPCCurrencyList[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCurrencylist($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Client\GRPCCurrencyList::class);
        $this->currencylist = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 2;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

}

