<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto

namespace Client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Client.GRPCReadClientResponse</code>
 */
class GRPCReadClientResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Client.GRPCClientList clientlist = 1;</code>
     */
    private $clientlist;
    /**
     * Generated from protobuf field <code>string status = 2;</code>
     */
    protected $status = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Client\GRPCClientList[]|\Google\Protobuf\Internal\RepeatedField $clientlist
     *     @type string $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Client::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Client.GRPCClientList clientlist = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getClientlist()
    {
        return $this->clientlist;
    }

    /**
     * Generated from protobuf field <code>repeated .Client.GRPCClientList clientlist = 1;</code>
     * @param \Client\GRPCClientList[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setClientlist($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Client\GRPCClientList::class);
        $this->clientlist = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 2;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

}

