<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto

namespace Client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Client.GRPCCountryList</code>
 */
class GRPCCountryList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string countryiso3 = 1;</code>
     */
    protected $countryiso3 = '';
    /**
     * Generated from protobuf field <code>string countrynicename = 2;</code>
     */
    protected $countrynicename = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $countryiso3
     *     @type string $countrynicename
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Client::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string countryiso3 = 1;</code>
     * @return string
     */
    public function getCountryiso3()
    {
        return $this->countryiso3;
    }

    /**
     * Generated from protobuf field <code>string countryiso3 = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCountryiso3($var)
    {
        GPBUtil::checkString($var, True);
        $this->countryiso3 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string countrynicename = 2;</code>
     * @return string
     */
    public function getCountrynicename()
    {
        return $this->countrynicename;
    }

    /**
     * Generated from protobuf field <code>string countrynicename = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCountrynicename($var)
    {
        GPBUtil::checkString($var, True);
        $this->countrynicename = $var;

        return $this;
    }

}

