<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto

namespace Client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Client.GRPCUpdateClientRequest</code>
 */
class GRPCUpdateClientRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string requestemail = 1;</code>
     */
    protected $requestemail = '';
    /**
     * Generated from protobuf field <code>string requestsessionid = 2;</code>
     */
    protected $requestsessionid = '';
    /**
     * Generated from protobuf field <code>string requestremoteipaddress = 3;</code>
     */
    protected $requestremoteipaddress = '';
    /**
     * Generated from protobuf field <code>string clientid = 4;</code>
     */
    protected $clientid = '';
    /**
     * Generated from protobuf field <code>string clientname = 5;</code>
     */
    protected $clientname = '';
    /**
     * Generated from protobuf field <code>string clientaddress = 6;</code>
     */
    protected $clientaddress = '';
    /**
     * Generated from protobuf field <code>string clientregion = 7;</code>
     */
    protected $clientregion = '';
    /**
     * Generated from protobuf field <code>string clientcountryid = 8;</code>
     */
    protected $clientcountryid = '';
    /**
     * Generated from protobuf field <code>string clientemail = 9;</code>
     */
    protected $clientemail = '';
    /**
     * Generated from protobuf field <code>string clientphone = 10;</code>
     */
    protected $clientphone = '';
    /**
     * Generated from protobuf field <code>string clientcurrency = 11;</code>
     */
    protected $clientcurrency = '';
    /**
     * Generated from protobuf field <code>string picname = 12;</code>
     */
    protected $picname = '';
    /**
     * Generated from protobuf field <code>string picemail = 13;</code>
     */
    protected $picemail = '';
    /**
     * Generated from protobuf field <code>string picphone = 14;</code>
     */
    protected $picphone = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $requestemail
     *     @type string $requestsessionid
     *     @type string $requestremoteipaddress
     *     @type string $clientid
     *     @type string $clientname
     *     @type string $clientaddress
     *     @type string $clientregion
     *     @type string $clientcountryid
     *     @type string $clientemail
     *     @type string $clientphone
     *     @type string $clientcurrency
     *     @type string $picname
     *     @type string $picemail
     *     @type string $picphone
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Client::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string requestemail = 1;</code>
     * @return string
     */
    public function getRequestemail()
    {
        return $this->requestemail;
    }

    /**
     * Generated from protobuf field <code>string requestemail = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestemail($var)
    {
        GPBUtil::checkString($var, True);
        $this->requestemail = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string requestsessionid = 2;</code>
     * @return string
     */
    public function getRequestsessionid()
    {
        return $this->requestsessionid;
    }

    /**
     * Generated from protobuf field <code>string requestsessionid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestsessionid($var)
    {
        GPBUtil::checkString($var, True);
        $this->requestsessionid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string requestremoteipaddress = 3;</code>
     * @return string
     */
    public function getRequestremoteipaddress()
    {
        return $this->requestremoteipaddress;
    }

    /**
     * Generated from protobuf field <code>string requestremoteipaddress = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestremoteipaddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->requestremoteipaddress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string clientid = 4;</code>
     * @return string
     */
    public function getClientid()
    {
        return $this->clientid;
    }

    /**
     * Generated from protobuf field <code>string clientid = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setClientid($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string clientname = 5;</code>
     * @return string
     */
    public function getClientname()
    {
        return $this->clientname;
    }

    /**
     * Generated from protobuf field <code>string clientname = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setClientname($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string clientaddress = 6;</code>
     * @return string
     */
    public function getClientaddress()
    {
        return $this->clientaddress;
    }

    /**
     * Generated from protobuf field <code>string clientaddress = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setClientaddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientaddress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string clientregion = 7;</code>
     * @return string
     */
    public function getClientregion()
    {
        return $this->clientregion;
    }

    /**
     * Generated from protobuf field <code>string clientregion = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setClientregion($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientregion = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string clientcountryid = 8;</code>
     * @return string
     */
    public function getClientcountryid()
    {
        return $this->clientcountryid;
    }

    /**
     * Generated from protobuf field <code>string clientcountryid = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setClientcountryid($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientcountryid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string clientemail = 9;</code>
     * @return string
     */
    public function getClientemail()
    {
        return $this->clientemail;
    }

    /**
     * Generated from protobuf field <code>string clientemail = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setClientemail($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientemail = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string clientphone = 10;</code>
     * @return string
     */
    public function getClientphone()
    {
        return $this->clientphone;
    }

    /**
     * Generated from protobuf field <code>string clientphone = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setClientphone($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientphone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string clientcurrency = 11;</code>
     * @return string
     */
    public function getClientcurrency()
    {
        return $this->clientcurrency;
    }

    /**
     * Generated from protobuf field <code>string clientcurrency = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setClientcurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientcurrency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string picname = 12;</code>
     * @return string
     */
    public function getPicname()
    {
        return $this->picname;
    }

    /**
     * Generated from protobuf field <code>string picname = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setPicname($var)
    {
        GPBUtil::checkString($var, True);
        $this->picname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string picemail = 13;</code>
     * @return string
     */
    public function getPicemail()
    {
        return $this->picemail;
    }

    /**
     * Generated from protobuf field <code>string picemail = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setPicemail($var)
    {
        GPBUtil::checkString($var, True);
        $this->picemail = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string picphone = 14;</code>
     * @return string
     */
    public function getPicphone()
    {
        return $this->picphone;
    }

    /**
     * Generated from protobuf field <code>string picphone = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setPicphone($var)
    {
        GPBUtil::checkString($var, True);
        $this->picphone = $var;

        return $this;
    }

}

