<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto

namespace Client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Client.GRPCReadClientRequest</code>
 */
class GRPCReadClientRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string requestemail = 1;</code>
     */
    protected $requestemail = '';
    /**
     * Generated from protobuf field <code>string requestsessionid = 2;</code>
     */
    protected $requestsessionid = '';
    /**
     * Generated from protobuf field <code>string requestremoteipaddress = 3;</code>
     */
    protected $requestremoteipaddress = '';
    /**
     * Generated from protobuf field <code>string clientid = 4;</code>
     */
    protected $clientid = '';
    /**
     * Generated from protobuf field <code>string clientname = 5;</code>
     */
    protected $clientname = '';
    /**
     * Generated from protobuf field <code>string clientregion = 6;</code>
     */
    protected $clientregion = '';
    /**
     * Generated from protobuf field <code>string clientcountryname = 7;</code>
     */
    protected $clientcountryname = '';
    /**
     * Generated from protobuf field <code>string clientemail = 8;</code>
     */
    protected $clientemail = '';
    /**
     * Generated from protobuf field <code>string picname = 9;</code>
     */
    protected $picname = '';
    /**
     * Generated from protobuf field <code>bool isactive = 10;</code>
     */
    protected $isactive = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $requestemail
     *     @type string $requestsessionid
     *     @type string $requestremoteipaddress
     *     @type string $clientid
     *     @type string $clientname
     *     @type string $clientregion
     *     @type string $clientcountryname
     *     @type string $clientemail
     *     @type string $picname
     *     @type bool $isactive
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Client::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string requestemail = 1;</code>
     * @return string
     */
    public function getRequestemail()
    {
        return $this->requestemail;
    }

    /**
     * Generated from protobuf field <code>string requestemail = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestemail($var)
    {
        GPBUtil::checkString($var, True);
        $this->requestemail = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string requestsessionid = 2;</code>
     * @return string
     */
    public function getRequestsessionid()
    {
        return $this->requestsessionid;
    }

    /**
     * Generated from protobuf field <code>string requestsessionid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestsessionid($var)
    {
        GPBUtil::checkString($var, True);
        $this->requestsessionid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string requestremoteipaddress = 3;</code>
     * @return string
     */
    public function getRequestremoteipaddress()
    {
        return $this->requestremoteipaddress;
    }

    /**
     * Generated from protobuf field <code>string requestremoteipaddress = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestremoteipaddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->requestremoteipaddress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string clientid = 4;</code>
     * @return string
     */
    public function getClientid()
    {
        return $this->clientid;
    }

    /**
     * Generated from protobuf field <code>string clientid = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setClientid($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string clientname = 5;</code>
     * @return string
     */
    public function getClientname()
    {
        return $this->clientname;
    }

    /**
     * Generated from protobuf field <code>string clientname = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setClientname($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string clientregion = 6;</code>
     * @return string
     */
    public function getClientregion()
    {
        return $this->clientregion;
    }

    /**
     * Generated from protobuf field <code>string clientregion = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setClientregion($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientregion = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string clientcountryname = 7;</code>
     * @return string
     */
    public function getClientcountryname()
    {
        return $this->clientcountryname;
    }

    /**
     * Generated from protobuf field <code>string clientcountryname = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setClientcountryname($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientcountryname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string clientemail = 8;</code>
     * @return string
     */
    public function getClientemail()
    {
        return $this->clientemail;
    }

    /**
     * Generated from protobuf field <code>string clientemail = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setClientemail($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientemail = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string picname = 9;</code>
     * @return string
     */
    public function getPicname()
    {
        return $this->picname;
    }

    /**
     * Generated from protobuf field <code>string picname = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setPicname($var)
    {
        GPBUtil::checkString($var, True);
        $this->picname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isactive = 10;</code>
     * @return bool
     */
    public function getIsactive()
    {
        return $this->isactive;
    }

    /**
     * Generated from protobuf field <code>bool isactive = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsactive($var)
    {
        GPBUtil::checkBool($var);
        $this->isactive = $var;

        return $this;
    }

}

