<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto

namespace Client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Client.GRPCCurrencyList</code>
 */
class GRPCCurrencyList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string currencyid = 1;</code>
     */
    protected $currencyid = '';
    /**
     * Generated from protobuf field <code>string currencyname = 2;</code>
     */
    protected $currencyname = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $currencyid
     *     @type string $currencyname
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Client::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string currencyid = 1;</code>
     * @return string
     */
    public function getCurrencyid()
    {
        return $this->currencyid;
    }

    /**
     * Generated from protobuf field <code>string currencyid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrencyid($var)
    {
        GPBUtil::checkString($var, True);
        $this->currencyid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string currencyname = 2;</code>
     * @return string
     */
    public function getCurrencyname()
    {
        return $this->currencyname;
    }

    /**
     * Generated from protobuf field <code>string currencyname = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrencyname($var)
    {
        GPBUtil::checkString($var, True);
        $this->currencyname = $var;

        return $this;
    }

}

