<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userapi.proto

namespace UserAPI;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>UserAPI.GRPCUserAPIList</code>
 */
class GRPCUserAPIList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string clientid = 2;</code>
     */
    protected $clientid = '';
    /**
     * Generated from protobuf field <code>string username = 3;</code>
     */
    protected $username = '';
    /**
     * Generated from protobuf field <code>string password = 4;</code>
     */
    protected $password = '';
    /**
     * Generated from protobuf field <code>string remoteipaddress = 5;</code>
     */
    protected $remoteipaddress = '';
    /**
     * Generated from protobuf field <code>string apiaccess = 6;</code>
     */
    protected $apiaccess = '';
    /**
     * Generated from protobuf field <code>string token = 7;</code>
     */
    protected $token = '';
    /**
     * Generated from protobuf field <code>string tokenexpiry = 8;</code>
     */
    protected $tokenexpiry = '';
    /**
     * Generated from protobuf field <code>string createdate = 9;</code>
     */
    protected $createdate = '';
    /**
     * Generated from protobuf field <code>string updatedate = 10;</code>
     */
    protected $updatedate = '';
    /**
     * Generated from protobuf field <code>bool isactive = 11;</code>
     */
    protected $isactive = false;
    /**
     * Generated from protobuf field <code>bool isdeleted = 12;</code>
     */
    protected $isdeleted = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $clientid
     *     @type string $username
     *     @type string $password
     *     @type string $remoteipaddress
     *     @type string $apiaccess
     *     @type string $token
     *     @type string $tokenexpiry
     *     @type string $createdate
     *     @type string $updatedate
     *     @type bool $isactive
     *     @type bool $isdeleted
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Userapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string clientid = 2;</code>
     * @return string
     */
    public function getClientid()
    {
        return $this->clientid;
    }

    /**
     * Generated from protobuf field <code>string clientid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setClientid($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string username = 3;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Generated from protobuf field <code>string username = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password = 4;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string remoteipaddress = 5;</code>
     * @return string
     */
    public function getRemoteipaddress()
    {
        return $this->remoteipaddress;
    }

    /**
     * Generated from protobuf field <code>string remoteipaddress = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRemoteipaddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->remoteipaddress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string apiaccess = 6;</code>
     * @return string
     */
    public function getApiaccess()
    {
        return $this->apiaccess;
    }

    /**
     * Generated from protobuf field <code>string apiaccess = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setApiaccess($var)
    {
        GPBUtil::checkString($var, True);
        $this->apiaccess = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string token = 7;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Generated from protobuf field <code>string token = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tokenexpiry = 8;</code>
     * @return string
     */
    public function getTokenexpiry()
    {
        return $this->tokenexpiry;
    }

    /**
     * Generated from protobuf field <code>string tokenexpiry = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setTokenexpiry($var)
    {
        GPBUtil::checkString($var, True);
        $this->tokenexpiry = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string createdate = 9;</code>
     * @return string
     */
    public function getCreatedate()
    {
        return $this->createdate;
    }

    /**
     * Generated from protobuf field <code>string createdate = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedate($var)
    {
        GPBUtil::checkString($var, True);
        $this->createdate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string updatedate = 10;</code>
     * @return string
     */
    public function getUpdatedate()
    {
        return $this->updatedate;
    }

    /**
     * Generated from protobuf field <code>string updatedate = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedate($var)
    {
        GPBUtil::checkString($var, True);
        $this->updatedate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isactive = 11;</code>
     * @return bool
     */
    public function getIsactive()
    {
        return $this->isactive;
    }

    /**
     * Generated from protobuf field <code>bool isactive = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsactive($var)
    {
        GPBUtil::checkBool($var);
        $this->isactive = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isdeleted = 12;</code>
     * @return bool
     */
    public function getIsdeleted()
    {
        return $this->isdeleted;
    }

    /**
     * Generated from protobuf field <code>bool isdeleted = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsdeleted($var)
    {
        GPBUtil::checkBool($var);
        $this->isdeleted = $var;

        return $this;
    }

}

