<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userapi.proto

namespace UserAPI;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>UserAPI.GRPCReadUserAPIResponse</code>
 */
class GRPCReadUserAPIResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .UserAPI.GRPCUserAPIList userapilist = 1;</code>
     */
    private $userapilist;
    /**
     * Generated from protobuf field <code>string status = 2;</code>
     */
    protected $status = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \UserAPI\GRPCUserAPIList[]|\Google\Protobuf\Internal\RepeatedField $userapilist
     *     @type string $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Userapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .UserAPI.GRPCUserAPIList userapilist = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserapilist()
    {
        return $this->userapilist;
    }

    /**
     * Generated from protobuf field <code>repeated .UserAPI.GRPCUserAPIList userapilist = 1;</code>
     * @param \UserAPI\GRPCUserAPIList[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserapilist($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \UserAPI\GRPCUserAPIList::class);
        $this->userapilist = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 2;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

}

